modLoader="javafml"
loaderVersion="[39,)"
license="GNU GPLv3"

[[mods]]
modId="jeg"
version="0.2.0"
displayName="Just Enough Guns"
authors="MigaMi"
credits="MrCrayfish, Bomb787"
description="The essentials needed for a survival friendly gun system done the right way!"

[[dependencies.jeg]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeg]]
    modId="framework"
    mandatory=true
    versionRange="[0.6.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeg]]
    modId="controllable"
    mandatory=false
    versionRange="[0.16.3,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.jeg]]
    modId="backpacked"
    mandatory=false
    versionRange="[2.1.9,)"
    ordering="AFTER"
    side="CLIENT"